version: 2
jobs:
  build:
    working_directory: ~/automation
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check

  publish_pxblue_publish:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc 
      - run:
          name: Publish @pxblue/publish
          command: |
            cd pxb-publish
            npx -p @pxblue/publish pxb-publish -p @pxblue/publish -b $CIRCLE_BRANCH

workflows:
  version: 2
  pxblue_cli:
    jobs:
      - build
      - publish_pxblue_publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
