version: 2
jobs:
  build:
    working_directory: ~/automation
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check

  publish_pxblue_publish:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc 
      - run:
          name: Publish @pxblue/publish
          command: |
            cd pxb-publish
            bash scripts/publish.sh -b $CIRCLE_BRANCH

  tag_test:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - run:
          name: Install GitHub CLI
          command: |
            wget https://github.com/github/hub/releases/download/v2.12.8/hub-linux-amd64-2.12.8.tgz
            tar zxvf hub-linux-amd64-2.12.8.tgz
            sudo mv hub-linux-amd64-2.12.8/bin/hub /usr/local/bin/hub
            sudo chmod +x /usr/local/bin/hub
      - run:
          name: auto tag test
          command: |
            cd pxb-tag
            bash scripts/tag.sh -b $CIRCLE_BRANCH

workflows:
  version: 2
  pxblue_automation:
    jobs:
      - tag_test