version: 2.1
orbs:
  gh: circleci/github-cli@1.0
jobs:
  build:
    working_directory: ~/automation
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check

  publish_pxblue_publish:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish @pxblue/publish
          command: |
            cd pxb-publish
            bash scripts/publish.sh -b $CIRCLE_BRANCH

  publish_pxblue_tag:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish @pxblue/tag
          command: |
            cd pxb-tag
            bash ../pxb-publish/scripts/publish.sh -b $CIRCLE_BRANCH

  tag_pxblue_publish:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - gh/setup
      - run:
          name: Tag @pxblue/publish
          command: |
            cd pxb-publish
            gh issue list

  tag_pxblue_tag:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - run:
          name: Tag @pxblue/tag
          command: |
            cd pxb-tag
            yarn add @pxblue/tag
            yarn pxb-tag -b $CIRCLE_BRANCH -s -pxb-tag

workflows:
  version: 2
  pxblue_automation:
    jobs:
      - build
      - publish_pxblue_publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
      - publish_pxblue_tag:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
      - tag_pxblue_publish:
          requires:
            - build
      - tag_pxblue_tag:
          requires:
            - publish_pxblue_tag
